jobs:
  - job: macosx
    pool:
      vmImage: xcode9-macos10.13
    steps:
      - script: |
          brew update
          brew install arpack eigen
        displayName: 'Install dependencies'
      - task: CMake@1
        displayName: 'Setup with CMake'
        inputs:
          cmakeArgs: -DCMAKE_BUILD_TYPE=Release $(cmakeOptions) ..
      - script: make
        displayName: 'Build with Make'
        workingDirectory: build
      - task: CopyFiles@2
        displayName: 'Copy to staging'
        inputs:
          contents: 'build/tapkee'
          targetFolder: $(Build.ArtifactStagingDirectory)
      - task: GithubRelease@0
        displayName: ‘Create GitHub Release’
        inputs:
          tag: latest-macosx
          githubConnection: lisitsyn
          repositoryName: lisitsyn/tapkee
  - job: ubuntu
    pool:
      vmImage: 'Ubuntu-16.04'
    steps:
      - script: |
          sudo apt-get install -y libeigen3-dev libarpack2-dev
      - task: CMake@1
        displayName: 'Setup with CMake'
        inputs:
          cmakeArgs: -DCMAKE_BUILD_TYPE=Release $(cmakeOptions) ..
      - script: make
        displayName: 'Build with Make'
        workingDirectory: build
      - task: CopyFiles@2
        displayName: 'Copy to staging'
        inputs:
          contents: 'build/tapkee'
          targetFolder: $(Build.ArtifactStagingDirectory)
      - task: GithubRelease@0
        displayName: ‘Create GitHub Release’
        inputs:
          tag: latest-linux
          githubConnection: lisitsyn
          repositoryName: lisitsyn/tapkee
  - job: windows
    pool:
      vmImage: vs2017-win2016
    steps:
      - task: CondaEnvironment@1
        displayName: Install dependencies
        inputs:
          createCustomEnvironment: True
          environmentName: shogun
          packageSpecs: 'python=3.6.* eigen'
          createOptions: '-c conda-forge'
          updateConda: false
      - task: CMake@1
        displayName: 'Setup with CMake'
        inputs:
          cmakeArgs: -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=$(CONDA_PREFIX)\Library $(cmakeOptions) ..
      - script: cmake --build .
        displayName: 'Build with CMake'
        workingDirectory: build
      - task: CopyFiles@2
        displayName: 'Copy to staging'
        inputs:
          contents: build\tapkee
          targetFolder: $(Build.ArtifactStagingDirectory)
      - task: GithubRelease@0
        displayName: ‘Create GitHub Release’
        inputs:
          tag: latest-windows
          githubConnection: lisitsyn
          repositoryName: lisitsyn/tapkee