jobs: 
  - job: ubuntu
    pool:
      vmImage: 'Ubuntu-16.04'
    steps:
      - task: CMake@1
        displayName: 'Build with CMake'
  - job: windows
    pool:
      vmImage: vs2017-win2016
    steps:
      - task: CMake@1
        displayName: 'Build with CMake'