jobs: 
  - job: ubuntu
    pool:
      vmImage: 'Ubuntu-16.04'
    steps:
      - task: CMake@1
        displayName: 'Build with CMake'
  - job: windows
    pool:
      vmImage: vs2017-win2016
    steps:
      - task: CMake@1
        displayName: 'Setup with CMake'
        cmakeArgs: -DCMAKE_BUILD_TYPE=Release $(cmakeOptions) ..
      - script: cmake --build .
        displayName: 'Build ($(buildConfiguration) $(buildPlatform))'
        workingDirectory: $(Build.SourcesDirectory)\build